### PR TITLE
run through markdown linter and do some cleanup as a small test

### PR DESCRIPTION
**Pull request by essess**
Not sure how well stuff like this will work outside of gerrithub. I think this would be a common case for others that want to contribute, but don't have access to gerrithub.

### CODE REVIEW

**Comment by fredcooke** [comment]
Even though this commit is already in the repo, Github thinks it conflicts. I guess it doesn't like rewritten Gerrit commits much and can't recognise it as being one and the same?

**Comment by essess** [comment]
Hmm. I wonder if this has something to do with the repo on my side being gone. I did this before I knew anything about how gerrithub fits into it all. How would you fix this ? 

I'll have to admit, I don't have much time or natural skill for things like this when I don't do it day-to-day.

**Comment by fredcooke** [comment]
I think the fix is obvious: just close/cancel the request. 

Gerrit modifies commits as part of its normal process. So your old commit as evident here is NOT in the master branch/repo. A modified version committed by Sean or Gerrit on Sean's behalf IS there. But they don't share the same identity at which point the Github code is going to be doing best guess based on time stamps and content, but cannot be sure - perhaps they simply do not implement that.

**Comment by essess** [comment]
done!

**Pull request closed without merging**
